import { loginPage } from '../../../pages/entity/loginPage'
import { corpCompany } from '../../../pages/entity/corpCompany'
describe('BC Unlimited Liability Company Registration', function () {

    it('start and complete a BC Unlimited Liability Company  Registration', function () {
      loginPage.visit(Cypress.env('BCRS_DOMAIN'))
      loginPage.verifyLanding()
      loginPage.logWithBCCard()
      corpCompany.changeAccountBen()
      corpCompany. navigateToNR()
      corpCompany.selectulcCompany()
      //corpCompany.assertNumberedCompany()
      corpCompany.startNumCompanyReg()
      corpCompany.surveyDialog()
      corpCompany.fillNamesTranslation()
      corpCompany.fillOfficeAddress()
      corpCompany.fillRecordsOffice()
      corpCompany.fillRegisterContactInfo()
      corpCompany.fillFolioNumber()
      corpCompany. moveToNextPage()
      corpCompany.fillCompletingParty()
      corpCompany.fillDirectorInfo()
      corpCompany.fillIncorpInfo()
      corpCompany. moveToNextPage()
      corpCompany.fillShareStructure()
      corpCompany.fillShareSeries()
      corpCompany. moveToNextPage()
      corpCompany.fillIncorporationAgreementForm()
      corpCompany.verifyAllStepsAreSavedAndResumed()
      corpCompany.clickCertifyAndEnterCourtOrder ()
      corpCompany.verifyPADPayment()
      corpCompany.verifyTheFilingIsCompleteAndDocuments()
    })
})